--From the table PUBLISHER, AUTHOR and BOOK perform the following queries:  
--Part – A: 
--1. List all books with their authors.
SELECT B.TITLE, A.AUTHORNAME
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID

--2. List all books with their publishers. 
SELECT B.TITLE, P.PUBLISHERNAME
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID

--3. List all books with their authors and publishers. 
SELECT B.TITLE,P.PUBLISHERNAME,A.AUTHORNAME
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID

--4. List all books published after 2010 with their authors and publisher and price.
SELECT B.TITLE, A.AUTHORNAME, P.PUBLISHERNAME, B.PRICE
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
WHERE B.PUBLICATIONYEAR > 2010

--5. List all authors and the number of books they have written.
SELECT A.AUTHORNAME, COUNT(B.BOOKID) AS TOTAL_BOOKS
FROM AUTHOR A
LEFT OUTER JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME

--6. List all publishers and the total price of books they have published. 
SELECT P.PUBLISHERNAME, SUM(B.PRICE) AS TOTAL_PRICE
FROM PUBLISHER P
INNER JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERNAME

--7. List authors who have not written any books.
SELECT A.AUTHORNAME
FROM AUTHOR A
LEFT OUTER JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
WHERE B.BOOKID IS NULL



--8. Display the total number of books written by each author along with the average price of their books.
SELECT A.AUTHORNAME, COUNT(B.BOOKID) AS TOTAL_BOOKS, AVG(B.PRICE) AS AVG_PRICE
FROM AUTHOR A
 JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME

--9. lists each publisher along with the total number of books they have published, sorted from highest to 
--lowest.
SELECT P.PUBLISHERNAME,COUNT(B.BOOKID) AS COUNT_BOOK
FROM PUBLISHER P
JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERNAME
ORDER BY COUNT_BOOK DESC


--10. Display number of books published each year.
SELECT PUBLICATIONYEAR, COUNT(*) AS TOTAL_BOOKS3
FROM BOOK
GROUP BY PUBLICATIONYEAR

--Part - B :
--11. List the publishers whose total book prices exceed 500, ordered by the total price. 
SELECT P.PUBLISHERNAME ,SUM(B.PRICE) AS TOTAL_PRICE
FROM PUBLISHER P
JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERNAME
HAVING SUM(B.PRICE) > 500
ORDER BY TOTAL_PRICE DESC

--12. List most expensive book for each author, sort it with the highest price. 
SELECT A.AUTHORNAME, MAX(B.PRICE) AS MAX_PRICE
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME
ORDER BY MAX_PRICE DESC


--13. Display publisher name and difference between maximum and minimum book price.
SELECT P.PUBLISHERNAME, MAX(B.PRICE) - MIN(B.PRICE) AS PRICE_DIFFERENCE
FROM PUBLISHER P
JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERNAME


--14. List publisher name and total price of books published each year. 
SELECT P.PUBLISHERNAME, B.PUBLICATIONYEAR, SUM(B.PRICE) AS TOTAL_PRICE
FROM PUBLISHER P
JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERNAME, B.PUBLICATIONYEAR


--15. Display author name and total price of books sorted by highest total price.
SELECT A.AUTHORNAME, SUM(B.PRICE) AS TOTAL_PRICE
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME
ORDER BY TOTAL_PRICE DESC


--From the above table EMPLOYEE_MASTER perform the following queries:  
--Part – C:
CREATE TABLE EMPLOYEE_MASTER(
EMPLOYEENO VARCHAR(25),
NAME VARCHAR(25),
MANAGERNO  VARCHAR(25)
)

INSERT INTO EMPLOYEE_MASTER
VALUES
('E01','TARUN',NULL),
('E02','ROHAN','E02'),
('E03','PRIYA','E01'),
('E04','MILAN','E03'),
('E05','JAY','E01'),
('E06','ANJANA','E04')

SELECT * FROM EMPLOYEE_MASTER
--16. Retrieve the names of employee along with their manager’s name from the Employee table.
SELECT E.NAME AS EMPLOYEE_NAME, M.NAME AS MANAGER_NAME
FROM EMPLOYEE_MASTER E
LEFT OUTER JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO


--17. Display employees who are managers.
SELECT DISTINCT M.NAME
FROM EMPLOYEE_MASTER E
JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO

--18. Display number of employees working under each manager.
SELECT M.NAME AS MANAGER_NAME, COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE_MASTER E
JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO
GROUP BY M.NAME

--19. Display the employee’s name along with their manager’s name and senior manager name.
SELECT E.NAME AS EMPLOYEE_NAME, M.NAME AS MANAGER_NAME, SM.NAME AS SENIOR_MANAGER_NAME
FROM EMPLOYEE_MASTER E
LEFT OUTER JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO
LEFT OUTER JOIN EMPLOYEE_MASTER SM
ON M.MANAGERNO = SM.EMPLOYEENO

--20. Display managers and count of employees under them in descending order.
SELECT M.NAME AS MANAGER_NAME, COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE_MASTER E
INNER JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO
GROUP BY M.NAME
ORDER BY TOTAL_EMPLOYEES DESC
